name: pre-commit

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.13
  PRE_COMMIT_VERSION: 4.2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}
          activate-environment: true
          cache-dependency-glob: |
            .github/workflows/pre-commit.yaml
      - name: Run pre-commit
        run: uv tool run pre-commit@${{ env.PRE_COMMIT_VERSION }} run --all-files
